### PR TITLE
Leaner downloadable package

### PR DESCRIPTION
**Pull request by weirdan**
This prevents misc files from being installed into `vendor` folder.

### CODE REVIEW

**Comment by llaville** [comment]
Sorry for the late reply, but I don't agree with this request, and I'll close it !

**Comment by weirdan** [comment]
Do you have some specific objections?

**Comment by llaville** [comment]
Personnaly, when I want to download source code without to clone a repo, I hate to missed some resources from the archive.

**Comment by weirdan** [comment]
Composer has `--prefer-source` option ([Docs](https://getcomposer.org/doc/03-cli.md#install-i)) that makes it use vcs repos instead of dist packages, specifically for when you need an entire package source. And `.gitattributes` does not affect the list of files you'll get this way.

**Comment by llaville** [comment]
Ok for Composer, but when you try to download archive directly via CURL or wget from the github.com server its always affect the list of files

**Comment by weirdan** [comment]
That's true. I did not realize someone does that.

**Pull request closed without merging**
